@startuml

class Client{
+ {static} void main(String[] args);
}

class Singleton{
- {static} final Singleton singleton;
- {static} final Singleton singleton = new Singleton();
- Singleton();
+ {static} Singleton getSingleton();
}

Singleton <-- Client

note right of Client:通过Singleton.getSingleton访问
@enduml