@startuml

class Singleton{
- Singleton();
+ void doSomething();
}

class SingletonFactory{
- {static} Singleton singleton;
+ {static} Singleton getSingleton();
}

SingletonFactory o--> Singleton
@enduml